### ISSUE TITLE
Task with name 'assembleRelease' not found in project ':app'.

### ISSUE THREAD

**Issue by zhengwei1209** [guofudong/KotlinAndroid#2]
运行报Task with name 'assembleRelease' not found in project ':app'.

**Comment by guofudong** [comment]
关闭工程，把工程下.idea的文件夹全部删掉，然后重新导入。

**Comment by sjj6995** [comment]
@guofudong 我这里不起作用，但是直接在 命令输入 ./gradlew :app:assembleDebug  可以执行。这是什么原因呢？
